name: Build QMK firmware

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    name: 'QMK Userspace Build'
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@main
    with:
      qmk_repo: qmk/qmk_firmware
      qmk_ref: master
      # Lots of hacks to put QMK stuff in the home directory, put keyboards in the qmk directory, and re-setup stuff
      preparation_command: cp -r qmk/* . && cp -r keyboards/* qmk_firmware/keyboards/ && qmk userspace-doctor

  publish:
    name: 'QMK Userspace Publish'
    uses: qmk/.github/.github/workflows/qmk_userspace_publish.yml@main
    if: always() && !cancelled()
    needs: build
